/* Content bank — separated from rendering. Edit text here. */
window.CONTENT = {
legacy19: [
"You are the melody everyone wishes they had written.",
"Seeing your beauty feels like sunrise after the longest night.",
"You are the only star my eyes keep finding in a crowded sky.",
"You are the sudden colour that makes an ordinary world feel alive.",
"You are a beautiful poem in a world addicted to small talk.",
"In a room full of breathtaking art, I think my eyes would still search for you.",
"Loving you feels strangely familiar, like remembering a beautiful life I have not lived yet.",
"If the universe were written in black ink, somehow you would still find a way to become colour.",
"If my heart ever needed a home, I think it would recognise yours.",
"Even after a thousand years of knowing your face, I think I would still notice something new.",
"Every love song makes a little more sense after meeting you.",
"I would choose you in every lifetime.",
"Even in a room full of stars, I would still look for your eyes.",
"If love ever needed a face, I think I would recognise yours.",
"You are the kind of beautiful words can only circle around.",
"You are my sunrise after every dark night.",
"You are the star I would navigate by.",
"I could spend a lifetime learning every shape of your expression.",
"I think some part of me was always looking for you."
],
sequencer: [
"I noticed you before I understood why.",
"Your voice has a way of slowing a room down.",
"There is a calm in your presence I have found nowhere else.",
"The pause before you smile might be my favourite part.",
"Thinking looks good on you. So does laughing mid-sentence.",
"You make silence comfortable. That is rarer than beauty.",
"Ordinary evenings turn memorable when you are in them.",
"I admire how you listen — fully, without rehearsing a reply.",
"Your laugh changes the temperature of a place.",
"Time moves differently around you. Slower, then too fast.",
"Beautiful without performance. That is the whole point.",
"Even your quiet has character.",
"The way your eyes change when you are genuinely happy — I keep that.",
"You turn normal conversations into ones I replay later.",
"Confidence sits naturally on you. Never loud, always clear.",
"Being near you makes me more deliberate, more honest.",
"I keep finding new details. It never levels off.",
"Your kindness is precise. You notice who needs softness.",
"Some people fill a room. You settle it.",
"You make the everyday feel arranged, even when it is not.",
"I don't think you realise how often you are the best part of a day.",
"Your focus is beautiful — the world narrows to what matters.",
"Getting excited about something suits you enormously.",
"Looking away, thinking, returning — I notice all of it.",
"You carry softness and strength without contradiction.",
"Familiar is the wrong word. Recognised is closer.",
"My attention wanders. It keeps landing on you.",
"You make home feel like a person, not a place.",
"There is music in how you speak when you care about something.",
"I like who I am when you are near. Quieter. Truer.",
"Beauty brought my eyes. Character kept them.",
"You never ask for attention. That is why you get mine.",
"I could describe your smile and still miss what it does to people.",
"Your presence never feels like background.",
"The world is noisy. You are the clear sentence in it.",
"I really do notice everything. Especially the small things.",
"There are things about you I never quite know how to explain.",
"How you say my name when it matters — I remember exactly.",
"Doubt leaves the room when you decide something.",
"Gentle with people, exacting with yourself. I see the cost.",
"A bad day, retold by you, becomes almost worth it.",
"You laugh at yourself first. That kind of ease can't be faked.",
"Curiosity looks alive in you. Everything gets your real attention.",
"The difference between your polite smile and your real one — I know it.",
"Grace, I am learning, is mostly how you treat people who can't help you.",
"Patience with slow things. Tea, stories, me thinking aloud.",
"You don't perform happiness. When it's real, your whole face agrees.",
"Somewhere between your second laugh and your quiet, I stayed.",
"And somehow, I still keep finding you."
],
noticings: [
"I notice how your presence changes the atmosphere without asking for attention.",
"I notice how ordinary moments feel less ordinary when you are there.",
"I notice the little things most people overlook — and I keep them.",
"I notice the way you go quiet when something actually matters.",
"I notice how you remember what people love, without being asked.",
"I notice how your eyes give you away before your words do.",
"I notice how you make strangers feel at ease within a minute.",
"I notice how you laugh with your whole face when it is real.",
"I notice how time with you never feels wasted, even doing nothing.",
"I notice how I started paying attention differently around you.",
"I notice the small pause before you answer something honest.",
"I notice how you tuck your hair back when you are concentrating.",
"I notice the way your voice softens when you talk about someone you love.",
"I notice how you check that everyone else is comfortable first.",
"I notice the exact moment your polite smile becomes a real one.",
"I notice how you linger a second longer on things you find beautiful.",
"I notice that you hum when you think no one is listening.",
"I notice how seriously you take promises, even small ones.",
"I notice how your eyes keep moving — always reading the room, always kind.",
"I notice that I notice you. Constantly. Without deciding to."
],
fragments: [
"the pause before a smile",
"the look that stays",
"the quiet after laughter",
"the moment a room feels different",
"the things language cannot hold",
"attention that feels like warmth",
"silence that feels like belonging",
"softness and strength, at once"
],
poems: [
{ title:"Finding", lines:[
"I was not looking for anything,","which is probably why I saw you clearly —",
"not as an answer, but as a question","I wanted to keep asking.",
"Days passed the way days do,","and somewhere inside them,","you stopped being someone I met","and started being someone I noticed","in everything."]},
{ title:"Eyes", lines:[
"At night the city keeps talking,","windows, traffic, the low hum of everyone —",
"and still, through all of it,","two points of stillness.",
"Not brighter than the rest. Deeper.","The kind of look that makes noise","forget itself. I hear less","and see more, whenever","your eyes find mine."]},
{ title:"Years", lines:[
"Give me years of mornings,","of your face across the table, half-lit,","of ordinary Tuesdays","nobody would photograph —",
"I would still be taking notes.","The curve of attention, the new angle","of an old laugh. Love, I am learning,","is not staying the same.","It is deepening without permission."]},
{ title:"Hands", lines:[
"You speak with your hands","when the words matter —",
"small certainties in the air,","as if shaping the thought","so it won't break.",
"I watch them the way some people","watch weather. Something honest","is arriving. I want","to be standing where it lands."]},
{ title:"Winter Light", lines:[
"January keeps its light low,","the city the colour of held breath.",
"You crossed the street through it","like it was arranged for you —",
"coat, cold cheeks, that unhurried pace","of someone who belongs to the day.","I understood, all at once,","what painters mean by warmth:","not brightness. Presence."]},
{ title:"Whisper", lines:[
"Stay a little longer.","The dark is softer with you in it.","Even silence","leans closer to listen."]}
],
why: [
"Because at first, honestly — your face. I won't pretend otherwise.",
"Because your presence steadies a room without asking for anything.",
"Because you listen like it matters, and it shows.",
"Because beauty is not the most interesting thing about you.",
"Because I keep discovering new details.",
"Because you make silence feel comfortable instead of empty.",
"Because your kindness is precise — you notice who needs softness.",
"Because you stay yourself in every room you enter.",
"Because calm follows you, and I have come to rely on it.",
"Because you remember what matters to people without being asked.",
"Because admiration grows the longer I look, instead of fading.",
"Because you carry softness and strength without contradiction.",
"Because ordinary days become reference points when you are in them.",
"Because you make me more deliberate, more honest, without a lecture.",
"Because choosing you never feels difficult.",
"Because you laugh with your whole face when it is real.",
"Because home stopped being a place and started being a person.",
"Because you take promises seriously, even small ones.",
"Because time with you never feels wasted, even doing nothing.",
"Because you make attention feel like warmth, not weight.",
"Because I have seen you tired, honest, unguarded — and stayed glad.",
"Because familiarity never dulled it. Every year added resolution.",
"Because out of everyone and everything, my attention keeps returning.",
"Because I would still choose you — every time."
],
neverEnough: [
"I could call you beautiful every day and still leave things unsaid.",
"I could describe your smile and still miss what it does to a room.",
"I could count the reasons I admire you and still forget the most important ones.",
"There are details about you that stay in my mind longer than they should.",
"I don't think you realise how much your presence changes the feeling of a room.",
"I could praise your eyes and still understate what attention feels like.",
"I could thank your calm and still owe it more.",
"I could admire your mind and still be catching up.",
"I could mention your warmth and still miss its precision.",
"I could talk about your laugh and still not replay it right.",
"I could study your face for years and still take notes.",
"I could call it love and still feel the word is too small.",
"I could keep you in every plan and still want more ordinary days.",
"I could say I choose you and still need to say it again tomorrow.",
"I could write about your voice and still not hold its low music.",
"I could admire your patience and still not deserve it.",
"I could learn every habit of yours and still be surprised.",
"I could memorise your face and still look up, startled, glad.",
"I could explain what you mean to me and still point, speechless.",
"I could spend a life describing you and still be mid-sentence.",
"I could love you carefully and still feel I am only beginning.",
"I could tell this story a hundred ways and still miss the best part.",
"I could hold every ordinary moment and still ask for one more.",
"Some things deepen instead of ending. You are the proof.",
"So I will keep saying it badly, and meaning it completely.",
"Still you. Still learning. Still glad."
],
ordinary: [
"Laughing at nothing, mid-kitchen, half-turned away.",
"Talking through a thought until it finally lands.",
"Walking nowhere in particular, unhurried.",
"Concentrating — the world narrowed to one thing.",
"Quiet beside me, both of us looking out.",
"Surprised, for half a second, completely yourself.",
"Excited about something small, and making it large.",
"Tired, honest, still kind.",
"Imperfect, unguarded, entirely you.",
"Nothing dramatic happening. Everything mattering."
],
memories: [
"the look that stayed in my mind longer than expected",
"the conversation I kept thinking about afterward",
"the moment I realised I was paying attention differently",
"the laugh I heard again hours later",
"the quiet that felt like agreement",
"the ordinary evening that became a reference point",
"the detail I noticed and never mentioned",
"the time slowed down without reason",
"the glance that said more than the sentence",
"the day that would have been forgettable — except you",
"the small kindness I still think about",
"the way home felt different after"
],
whatif: [
"What if I had met you earlier — would I have known, or needed the years?",
"What if we had crossed paths somewhere completely different?",
"What if there were a thousand versions of my life?",
"I think in most of them, I would still hope one road led to you.",
"And in this one — the only one I get — I would still find you.",
"Still notice. Still choose. Still stay."
],
finalPoem: ["I looked up once in a crowded room,","and the noise thinned to a single point — you.",
"Not the brightest thing there. The truest.","Years could pass over that look","and I would still be learning it.",
"Mornings, winters, ordinary light,","your face half-turned toward something","only you had noticed. I followed","not to possess, but to witness.",
"Choose, the world kept saying. Decide.","I had. Quietly, early, and again","every day since — in silence, in laughter,","in the thousand small elections of attention.",
"If time gave me every life it owns,","I would spend each one the same way:","looking, until I found you,","staying, until it meant something.",
"Still you. Every time."]
};
